-- migration: create_audit_log_partitioned_if_absent
-- id: 01M2Z040JTSGF3V0AQMP583BDA
--
-- On a database built from migrations alone, audit_log does not exist: no
-- migration creates it, the ORM does, at first boot. partition_audit_log
-- therefore finds nothing and skips, and the deployment ends up with a PLAIN
-- audit_log. drop_audit_log_partitions_before can then never reclaim anything,
-- which is the growth problem partitioning was introduced to solve (issuedb
-- #20, reproduced: relkind 'r' on a fresh container after boot).
--
-- Creating it here, partitioned, means create_all finds it present and skips
-- it. Column types mirror auth.audit.AuditLog exactly; PRIMARY KEY is
-- (id, timestamp) because PostgreSQL requires the partition key in every
-- unique constraint, which is the same compromise partition_audit_log made.
--
-- Four cases, and only one of them does anything:
--
--   absent                        create it partitioned with runway  <- fresh
--   present and partitioned       nothing                            <- vm-2
--   present, plain, EMPTY         drop and recreate partitioned      <- a boot
--                                                                       that
--                                                                       beat the
--                                                                       migration
--   present, plain, HAS ROWS      leave it; partition_audit_log owns that
--                                 conversion and it needs to copy data
--
-- The third case matters because the runbook's ordering (migrate, then deploy)
-- is advice, not a mechanism: anyone who boots the app first gets a plain
-- empty table, and skipping it would leave the defect in place for exactly the
-- people who did it in the wrong order.

-- migrate: up

DO $c$
DECLARE
    v_kind   "char";
    v_rows   bigint;
    v_month  date;
    v_max    date;
BEGIN
    IF to_regnamespace('auth_rbac') IS NULL THEN
        RAISE NOTICE 'auth_rbac absent; nothing to do';
        RETURN;
    END IF;

    SELECT c.relkind INTO v_kind
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'auth_rbac' AND c.relname = 'audit_log';

    IF v_kind = 'p' THEN
        RAISE NOTICE 'auth_rbac.audit_log already partitioned; nothing to do';
        RETURN;
    END IF;

    IF v_kind = 'r' THEN
        EXECUTE 'SELECT count(*) FROM auth_rbac.audit_log' INTO v_rows;
        IF v_rows > 0 THEN
            RAISE NOTICE 'auth_rbac.audit_log is plain and holds % row(s); '
                'partition_audit_log owns that conversion, leaving it alone', v_rows;
            RETURN;
        END IF;
        RAISE NOTICE 'auth_rbac.audit_log is plain and empty; recreating it partitioned';
        DROP TABLE auth_rbac.audit_log;
    END IF;

    CREATE TABLE auth_rbac.audit_log (
        id          integer GENERATED BY DEFAULT AS IDENTITY,
        "timestamp" timestamp without time zone NOT NULL,
        client_id   text NOT NULL,
        "user"      character varying(64),
        action      character varying(50) NOT NULL,
        resource    text,
        details     text,
        ip_address  character varying(45),
        user_agent  text,
        success     integer,
        PRIMARY KEY (id, "timestamp")
    ) PARTITION BY RANGE ("timestamp");

    -- A trap, not a home: rows here mean the provisioner fell behind, and
    -- retention deliberately skips this partition.
    CREATE TABLE auth_rbac.audit_log_default
        PARTITION OF auth_rbac.audit_log DEFAULT;

    -- One month behind for clock skew, twelve ahead, matching what
    -- partition_audit_log leaves on a converted database.
    v_month := (date_trunc('month', now()) - interval '1 month')::date;
    v_max   := (date_trunc('month', now()) + interval '12 months')::date;
    WHILE v_month <= v_max LOOP
        EXECUTE format(
            'CREATE TABLE auth_rbac.%I PARTITION OF auth_rbac.audit_log '
            'FOR VALUES FROM (%L) TO (%L)',
            'audit_log_' || to_char(v_month, 'YYYY_MM'),
            v_month, (v_month + interval '1 month')::date);
        v_month := (v_month + interval '1 month')::date;
    END LOOP;

    CREATE INDEX IF NOT EXISTS ix_auth_rbac_audit_log_client_id
        ON auth_rbac.audit_log (client_id);
    CREATE INDEX IF NOT EXISTS ix_auth_rbac_audit_log_user
        ON auth_rbac.audit_log ("user");
    CREATE INDEX IF NOT EXISTS ix_auth_rbac_audit_log_timestamp
        ON auth_rbac.audit_log ("timestamp");

    RAISE NOTICE 'auth_rbac.audit_log created partitioned with % partitions',
        (SELECT count(*) FROM pg_inherits WHERE inhparent = 'auth_rbac.audit_log'::regclass);
END;
$c$;

-- migrate: down

DO $d$
BEGIN
    RAISE NOTICE 'not reversible: dropping audit_log would destroy the audit '
        'trail. Remove it by hand if a rollback genuinely requires it.';
END;
$d$;
