"""Tenant key rotation: move a namespace to a fresh client key atomically."""

import logging
from typing import Any, Dict, List, Tuple, cast

from sqlalchemy import Table, func, select, update

from auth.audit import client_fingerprint
from auth.models.sql import (
    AuthApiKey,
    AuthGroup,
    AuthMembership,
    AuthPermission,
    AuthTenantSettings,
)
from auth.services.base import validate_client_key
from auth.services.keys import ApiKeyMixin

logger = logging.getLogger(__name__)


class RotationMixin(ApiKeyMixin):
    """Re-key an entire tenant namespace in one transaction."""

    # --- Key rotation ----------------------------------------------------

    @staticmethod
    def _rotate_cell(enc, stored, old_creator: str, new_creator: str):
        """Re-key one encrypted cell from ``old_creator`` to ``new_creator``.

        Returns the ciphertext sealed under the new creator, or ``None`` when
        the cell is empty (nothing to write). Mirrors
        ``scripts/reencrypt_pertenant.reencrypt_value`` but decrypts under the
        OLD creator and re-encrypts under the NEW one — necessary because field
        keys are derived per-creator (HKDF), so ciphertext is bound to the
        creator that wrote it. Legacy global-key ciphertext and never-encrypted
        plaintext both recover their plaintext and are then sealed (v2) under
        the new key. A value that looks like ciphertext but fails authentication
        raises ``InvalidCiphertextError`` rather than being silently rewritten.
        """
        from auth.encryption import InvalidCiphertextError

        if not stored:
            return None
        try:
            plaintext = enc.decrypt(stored, old_creator)
        except InvalidCiphertextError:
            raise
        except ValueError:
            plaintext = stored  # legacy plaintext row (never encrypted)
        return enc.encrypt(plaintext, new_creator)

    def rotate_client_key(self, new_key: str) -> Dict[str, Any]:
        """Atomically move this client's namespace to a fresh key (cutover).

        Reassigns every ``auth_group`` / ``auth_membership`` / ``auth_permission``
        / ``auth_api_key`` row from ``creator = self.client`` (the old key) to
        ``creator = new_key`` in a single transaction, then returns the migrated
        row counts. Junction tables reference row ids and follow automatically,
        so they need no change.

        When field encryption is enabled the encrypted columns (``user`` /
        ``name`` / ``description`` / ``label``) are cryptographically bound to
        the creator, so each is decrypted under the old key and re-encrypted
        under the new key in the same pass, keeping the new namespace
        equality-queryable. When encryption is off the columns are plaintext and
        a single bulk ``creator`` update per table suffices. Per-user API-key
        hashes are creator-independent and survive rotation unchanged — issued
        secrets keep validating under the new tenant key.

        The new key is generated by the caller (server-side) and is a fresh
        UUID4, so the target namespace is empty and the ``UNIQUE(creator, ...)``
        constraints cannot conflict. On any error the transaction is rolled back
        — leaving the old namespace intact — and the error re-raised.
        """
        if not validate_client_key(new_key):
            raise ValueError("new_key must be a valid UUID4")
        if new_key == self.client:
            raise ValueError("new_key must differ from the current key")

        from auth.encryption import field_encryption

        # Serialize against concurrent writes/rotation for this tenant so the
        # scan-then-update pass below sees a stable row set (no stranded insert,
        # no clobbered update). Held until this transaction commits/rolls back.
        self._lock_tenant()

        old = self.client
        # (result label, table, encrypted column names)
        # __table__ is a Table at runtime; the declarative stubs type it as the
        # broader FromClause, so cast for the DML/column APIs below.
        # auth_api_key carries TWO encrypted cells; its key_hash/key_id are
        # creator-independent on purpose and move untouched, so issued secrets
        # keep validating under the new tenant key.
        targets: List[Tuple[str, Table, List[str]]] = [
            ("roles", cast(Table, AuthGroup.__table__), ["description"]),
            ("memberships", cast(Table, AuthMembership.__table__), ["user"]),
            ("permissions", cast(Table, AuthPermission.__table__), ["name"]),
            ("api_keys", cast(Table, AuthApiKey.__table__), ["user", "label"]),
            ("settings", cast(Table, AuthTenantSettings.__table__), []),
        ]
        migrated: Dict[str, int] = {}
        try:
            for label, table, enc_cols in targets:
                if field_encryption.enabled and field_encryption.encryptor is not None:
                    # Re-key each row's encrypted cells (bound to creator), then
                    # flip creator — all in the same UPDATE.
                    rows = self.db.execute(
                        select(table.c.id, *(table.c[col] for col in enc_cols)).where(
                            table.c.creator == old
                        )
                    ).fetchall()
                    for fetched in rows:
                        row_id = fetched[0]
                        values: Dict[str, Any] = {"creator": new_key}
                        for offset, col in enumerate(enc_cols, start=1):
                            new_cell = self._rotate_cell(
                                field_encryption.encryptor,
                                fetched[offset],
                                old,
                                new_key,
                            )
                            if new_cell is not None:
                                values[col] = new_cell
                        self.db.execute(
                            update(table).where(table.c.id == row_id).values(values)
                        )
                    migrated[label] = len(rows)
                else:
                    # Plaintext columns: count, then one bulk creator update.
                    count = self.db.execute(
                        select(func.count())
                        .select_from(table)
                        .where(table.c.creator == old)
                    ).scalar_one()
                    self.db.execute(
                        update(table)
                        .where(table.c.creator == old)
                        .values(creator=new_key)
                    )
                    migrated[label] = int(count)
            self._commit()
        except Exception:
            logger.exception(
                "rotate_client_key failed (old_creator=%s)", client_fingerprint(old)
            )
            self.db.rollback()
            raise

        # The old scope is now empty; point this instance at the new key so any
        # further use is consistent with what was just committed.
        self.client = new_key
        return {"new_key": new_key, "migrated": migrated}
